### ISSUE TITLE
Feature Request: Please add a free Text field

### ISSUE THREAD

**Issue by jochenpa** [zwiebert/tronferno-mcu#5]
Hello

It would be nice to have a free Text field for every shutter and also for the group (E set to A).
This is also available in the original 2411 RC.

Jochen

PS: Do you have a amazon wishlist or another way to contribute?

**Comment by zwiebert** [comment]
Hello Jochen, thanks for the suggestion. I'll do that.

The Android app currently allows configuring names like the 2411 does, but stores these on the phone, since it was too complicated back then to store on the ESP8266 MCU. I'll change this so the names are then available on web-interface and  FHEM module. 

Thanks for your feedback, which is already a nice contribution.

-Bert

**Comment by jochenpa** [comment]
Thank you.
